-- MySQL Script generated by MySQL Workbench
-- Sat Dec  9 19:29:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema final_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final_project` DEFAULT CHARACTER SET utf8mb3 ;
USE `final_project` ;

-- -----------------------------------------------------
-- Table `final_project`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`calendar` ;

CREATE TABLE IF NOT EXISTS `final_project`.`calendar` (
  `date` DATETIME NOT NULL,
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`charges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`charges` ;

CREATE TABLE IF NOT EXISTS `final_project`.`charges` (
  `idcharges` INT NOT NULL AUTO_INCREMENT,
  `charge_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcharges`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`cities` ;

CREATE TABLE IF NOT EXISTS `final_project`.`cities` (
  `idcity` VARCHAR(5) NOT NULL,
  `id_country` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcity`),
  INDEX `idcountry_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `idcountry`
    FOREIGN KEY (`id_country`)
    REFERENCES `final_project`.`countries` (`idcountries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`countries` ;

CREATE TABLE IF NOT EXISTS `final_project`.`countries` (
  `idcountries` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`idcountries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`employees` ;

CREATE TABLE IF NOT EXISTS `final_project`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `id_salary` INT NOT NULL,
  `id_charge` INT NOT NULL,
  PRIMARY KEY (`idemployees`),
  INDEX `idsalary_idx` (`id_salary` ASC) VISIBLE,
  INDEX `idcharge_idx` (`id_charge` ASC) VISIBLE,
  CONSTRAINT `idsalary`
    FOREIGN KEY (`id_salary`)
    REFERENCES `final_project`.`salary` (`idsalary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcharge`
    FOREIGN KEY (`id_charge`)
    REFERENCES `final_project`.`charges` (`idcharges`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`parking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`parking` ;

CREATE TABLE IF NOT EXISTS `final_project`.`parking` (
  `idparking` INT NOT NULL AUTO_INCREMENT,
  `parking_number` INT NOT NULL,
  `zone` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idparking`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `final_project`.`pools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`pools` ;

CREATE TABLE IF NOT EXISTS `final_project`.`pools` (
  `idpools` INT NOT NULL AUTO_INCREMENT,
  `pool_number` INT NOT NULL,
  PRIMARY KEY (`idpools`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`reservation` ;

CREATE TABLE IF NOT EXISTS `final_project`.`reservation` (
  `idreservation` INT NOT NULL AUTO_INCREMENT,
  `id_users` INT NOT NULL,
  `id_parking` INT NULL,
  `id_rooms` INT NULL,
  `id_employee` INT NOT NULL,
  `id_pool` INT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `status_description` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idreservation`),
  INDEX `iduser_idx` (`id_users` ASC) VISIBLE,
  INDEX `idparking_idx` (`id_parking` ASC) VISIBLE,
  INDEX `date_idx` (`start_date` ASC) VISIBLE,
  INDEX `idroom_idx` (`id_rooms` ASC) VISIBLE,
  INDEX `idemployee_idx` (`id_employee` ASC) VISIBLE,
  INDEX `idpool_idx` (`id_pool` ASC) VISIBLE,
  CONSTRAINT `idparking`
    FOREIGN KEY (`id_parking`)
    REFERENCES `final_project`.`parking` (`idparking`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_users`)
    REFERENCES `final_project`.`users` (`idusers`),
  CONSTRAINT `date`
    FOREIGN KEY (`start_date`)
    REFERENCES `final_project`.`calendar` (`date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idroom`
    FOREIGN KEY (`id_rooms`)
    REFERENCES `final_project`.`rooms` (`idrooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idemployee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `final_project`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpool`
    FOREIGN KEY (`id_pool`)
    REFERENCES `final_project`.`pools` (`idpools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `final_project`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`rooms` ;

CREATE TABLE IF NOT EXISTS `final_project`.`rooms` (
  `idrooms` INT NOT NULL AUTO_INCREMENT,
  `room_number` INT NOT NULL,
  `zone` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`salary` ;

CREATE TABLE IF NOT EXISTS `final_project`.`salary` (
  `salary` DECIMAL(12) NOT NULL,
  `id_employee` INT NOT NULL,
  `idsalary` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idsalary`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`user_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`user_category` ;

CREATE TABLE IF NOT EXISTS `final_project`.`user_category` (
  `iduser_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `discount` INT NULL,
  PRIMARY KEY (`iduser_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project`.`users` ;

CREATE TABLE IF NOT EXISTS `final_project`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `id_city` VARCHAR(5) NOT NULL,
  `id_category` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`),
  INDEX `idcity_idx` (`id_city` ASC) VISIBLE,
  INDEX `idcategory_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `idcity`
    FOREIGN KEY (`id_city`)
    REFERENCES `final_project`.`cities` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcategory`
    FOREIGN KEY (`id_category`)
    REFERENCES `final_project`.`user_category` (`iduser_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
